name: Task PR Check

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    container:
      image: seika/cxx-test:latest
    steps:
      - uses: actions/checkout@v3
      - name: Validate branch name
        run: |
          if [[ ! $GITHUB_HEAD_REF =~ ^[a-z]+-[a-z]+-task[0-9]+$ ]]; then
            echo "::error::Branch name must be in format 'surname-name-taskN'"
            exit 1
          fi

  build:
    needs: [validate]
    runs-on: ubuntu-latest
    container:
      image: seika/cxx-test:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          cd members/${GITHUB_HEAD_REF%-task*}
          mkdir -p build && cd build
          cmake .. && make
