name: Task PR Check

on: [pull_request]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate branch and structure
        run: |
          if [[ ! $GITHUB_HEAD_REF =~ ^[a-z]+-[a-z]+-task[ehm][1-9]$|^[a-z]+-[a-z]+-task[ehm]10$ ]]; then
            echo "::error::Branch name must be 'surname-name-task{e,m,h}{1..10}'"
            exit 1
          fi
          
          USER_DIR="${GITHUB_HEAD_REF%-task*}"
          TASK_NAME="${GITHUB_HEAD_REF##*-}"
          TASK_DIR="members/$USER_DIR/task$TASK_NAME"
          
          if [ ! -d "$TASK_DIR" ]; then
            echo "::error::Directory $TASK_DIR not found"
            exit 1
          fi

  build:
    needs: [validate]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up C++ environment
        uses: actions/setup-cpp@v2
        with:
          gcc-version: '11'
      - name: Install CMake
        run: sudo apt-get install -y cmake
      - name: Build and test
        run: |
          USER_DIR="${GITHUB_HEAD_REF%-task*}"
          TASK_NAME="${GITHUB_HEAD_REF##*-}"
          cd "members/$USER_DIR/task$TASK_NAME"
          
          mkdir -p build && cd build
          cmake .. && make
          
          if [ -f "solution" ]; then
            ./solution
          fi
