name: Task Push Check

on: 
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: seika/cxx-test:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
          mkdir -p build
          cd build
          cmake ..
          make
      - name: Run tests
        run: |
          cd build
          ctest --output-on-failure
