name: Task Push Check

on: 
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: seika/cxx-test:latest
    steps:
      - uses: actions/checkout@v3
      - name: Build all
        run: |
          for dir in members/*; do
            cd $dir && mkdir -p build && cd build
            cmake .. && make
            cd ../../..
          done
